services:
  row-app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8501:8501"

    volumes:
      - /home:/home
      - /data:/data
      - /home/gve/.streamlit:/root/.streamlit

    extra_hosts:
      - "host.docker.internal:host-gateway"